application: regexplanet-python
version: 1
runtime: python27
api_version: 3
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: regexplanet-api.app


