application: regexplanet-python
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /favicon.svg
  static_files: favicon.svg
  upload: favicon.svg
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: regexplanet-api.app
env_variables:
  COMMIT: dev
  LASTMOD: dev
